resources:
  'entity:node':
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - oauth
    POST:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - oauth
    DELETE:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - oauth
    PATCH:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - oauth
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
